version: '3.8'

services:
  app:
      image: gseldon/yc_certificate_manager_get:$TAG
      container_name: certificate_manager
      environment:
        - TZ=Europe/Moscow
      volumes:
        - ./app/service_private_key.pem:/app/service_private_key.pem:ro
        - ./app/setting.py:/app/setting.py:ro
        - certificates:/certificate_folder
  nginx:
      image: nginx:latest
      environment:
        - TZ=Europe/Moscow
      volumes:
        - certificates:/certificate_folder:ro

volumes:
  certificates: {}